server:
  http_listen_port: 3200

distributor:
  otlp:
    protocols:
      grpc:
      http:

ingester:
  trace_idle_period: 10s
  trace_flush_threshold: 1mb

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal   