services:
    # --- Microservices (Using Rosetta/AMD64) ---
  shoehub:
    image: aussiearef/shoehub
    platform: linux/amd64
    ports:
      - "8001:8080"

  orderservice:
    image: aussiearef/orderservice
    platform: linux/amd64

  paymentservice:
    image: aussiearef/paymentservice
    platform: linux/amd64

  stimulator:
    image: aussiearef/stimulator
    platform: linux/amd64
    depends_on:
      - orderservice
      - paymentservice